### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by samhstn** [dwyl/amp-elixir#3]
Travis says that I don't have the admin access required to enable travis builds for this repository, @iteles @nelsonic could you enable builds here please: https://travis-ci.org/dwyl/amp-elixir
![screen shot 2017-04-04 at 22 04 37](https://cloud.githubusercontent.com/assets/15983736/24678569/ececc96e-1982-11e7-8d24-bf97cd1791a3.png)

**Comment by nelsonic** [comment]
@shouston3 I see the same message:
![image](https://cloud.githubusercontent.com/assets/194400/24685537/1cac168c-19a6-11e7-98c2-fc512ee15df2.png)
Had to go: https://travis-ci.org/profile/dwyl and click on "Sync account":
![image](https://cloud.githubusercontent.com/assets/194400/24685581/6a39e834-19a6-11e7-9383-f01b71f3ad0a.png)
Then "enable" the repo:
![image](https://cloud.githubusercontent.com/assets/194400/24685597/82b8a3d2-19a6-11e7-8521-67d4e238683f.png)
After:
![image](https://cloud.githubusercontent.com/assets/194400/24685605/8d571c7e-19a6-11e7-952a-33c2c85c1cd1.png)

@shouston3 let me know when it's running builds. 👍

**Comment by samhstn** [comment]
Sorry about that. Yep, travis is now doing it's thing

Thanks @nelsonic
